/**
 * Generate the luck baselines and write src/grader/baselines.ts.
 * REQUIREMENTS 4A.7 (deal-luck and pegging-luck baselines).
 *
 *   npm run gen:baselines                 # default sample sizes
 *   npm run gen:baselines -- 100000 50000 # dealLuckN peggingN (field-test scale)
 *
 * Deals are shuffled with a FIXED seed so regeneration is reproducible. The
 * default sizes finish in well under a minute; the spec asks for >= 100,000 for
 * the real baselines — bump the args for the field test.
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { makeDeck, type Card } from '../src/cards.js';
import { seededRng } from '../src/rng.js';
import { dealHands, type PlayerCount } from '../src/deal.js';
import { expectedHandValue } from '../src/grader/expected-hand.js';
import { gradeDiscard } from '../src/grader/discard.js';
import { combinations } from '../src/grader/combinatorics.js';
import { replayPegging } from '../src/grader/pegging-policy.js';
import {
  ALL_CASES,
  caseKey,
  sideOfSeat,
  type BaselineCaseKey,
} from '../src/grader/baseline-cases.js';
import { seatUnitMap } from '../src/show.js';

const PLAYER_COUNTS: PlayerCount[] = [2, 3, 4];
const DEALER_SEAT = 0;
const CRIB_ITERATIONS = 120;

function bestKeepByHand(dealt: Card[], discardsEach: number): Card[] {
  let bestKeep: Card[] = [];
  let bestVal = -Infinity;
  for (const discard of combinations(dealt, discardsEach)) {
    const keep = dealt.filter((c) => !discard.includes(c));
    const v = expectedHandValue(keep, dealt);
    if (v > bestVal) {
      bestVal = v;
      bestKeep = keep;
    }
  }
  return bestKeep;
}

interface Accumulator {
  sum: number;
  count: number;
}

function emptyAcc(): Record<BaselineCaseKey, Accumulator> {
  const rec = {} as Record<BaselineCaseKey, Accumulator>;
  for (const k of ALL_CASES) rec[k] = { sum: 0, count: 0 };
  return rec;
}

function averages(
  acc: Record<BaselineCaseKey, Accumulator>,
): Record<BaselineCaseKey, number> {
  const out = {} as Record<BaselineCaseKey, number>;
  for (const k of ALL_CASES) {
    out[k] = acc[k].count > 0 ? acc[k].sum / acc[k].count : 0;
  }
  return out;
}

function main(argv: string[]): void {
  const dealLuckN = argv[0] ? Number(argv[0]) : 2000;
  const peggingN = argv[1] ? Number(argv[1]) : 8000;

  const rng = seededRng('deer-camp-baselines-v1');
  const dealLuckAcc = emptyAcc();
  const peggingAcc = emptyAcc();

  for (const pc of PLAYER_COUNTS) {
    const unitMap = seatUnitMap(pc);

    // Deal-luck baseline: average best-discard value per case.
    for (let i = 0; i < dealLuckN; i++) {
      const deck = rng.shuffle(makeDeck());
      const { hands } = dealHands(pc, deck);
      for (let seat = 0; seat < pc; seat++) {
        const side = sideOfSeat(pc, seat, DEALER_SEAT);
        const cfg = hands[seat]!;
        const grade = gradeDiscard({
          playerCount: pc,
          dealt: cfg,
          chosenDiscard: cfg.slice(0, pc === 2 ? 2 : 1),
          cribIsMine: side === 'dealer',
          seed: `baseline:${pc}:${i}:${seat}`,
          cribSimIterations: CRIB_ITERATIONS,
        });
        const acc = dealLuckAcc[caseKey(pc, side)];
        acc.sum += grade.best.value;
        acc.count += 1;
      }
    }

    // Pegging-luck baseline: average standard-policy pegging per unit per case.
    const discardsEach = pc === 2 ? 2 : 1;
    for (let i = 0; i < peggingN; i++) {
      const deck = rng.shuffle(makeDeck());
      const { hands } = dealHands(pc, deck);
      const keptHands = hands.map((hand) => bestKeepByHand(hand, discardsEach));
      const { perUnit } = replayPegging(keptHands, DEALER_SEAT, pc);
      const unitCount = Math.max(...unitMap) + 1;
      for (let unit = 0; unit < unitCount; unit++) {
        const side = unit === unitMap[DEALER_SEAT]! ? 'dealer' : 'nondealer';
        const acc = peggingAcc[caseKey(pc, side)];
        acc.sum += perUnit[unit]!;
        acc.count += 1;
      }
    }
    console.error(`done ${pc}-player`);
  }

  const dealLuck = averages(dealLuckAcc);
  const peggingLuck = averages(peggingAcc);

  const body = `/**
 * GENERATED by scripts/generate-baselines.ts — do not edit by hand.
 * Luck baselines for 4A.7. Regenerate with: npm run gen:baselines
 */

import { type BaselineSet } from './baseline-cases.js';

export const BASELINES: BaselineSet = {
  meta: {
    generatedAt: ${JSON.stringify(new Date().toISOString())},
    dealLuckSamples: ${dealLuckN},
    peggingSamples: ${peggingN},
    cribIterations: ${CRIB_ITERATIONS},
  },
  dealLuck: ${JSON.stringify(dealLuck, null, 4).replace(/\n/g, '\n  ')},
  peggingLuck: ${JSON.stringify(peggingLuck, null, 4).replace(/\n/g, '\n  ')},
};
`;

  const here = dirname(fileURLToPath(import.meta.url));
  const out = join(here, '..', 'src', 'grader', 'baselines.ts');
  writeFileSync(out, body);
  console.error(`wrote ${out}`);
  console.error(JSON.stringify({ dealLuck, peggingLuck }, null, 2));
}

main(process.argv.slice(2));
