/**
 * Generate docs/ENGINE_CHECK.md: a by-hand verification worksheet.
 *   npm run worksheet
 *
 * Every number in the output is produced by the LIVE engine. The "textbook"
 * column is the independently-known correct answer, so a mismatch is a bug.
 * This supports the Phase 1 acceptance gate (Section 9): Kyle checks a set of
 * hands by hand and agrees with the scores and rankings.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { parseCards, type Card } from '../src/cards.js';
import { scoreHand, describeScore } from '../src/score-hand.js';
import { scorePegCard } from '../src/score-pegging.js';
import { countShow } from '../src/show.js';
import { gradeDiscard } from '../src/grader/discard.js';
import { rankPhrase, rankOf } from '../src/grader/rank.js';
import { hindsightAtCut, verdict, cutFavored } from '../src/grader/hindsight.js';

const h = (s: string): Card[] => parseCards(s.split(/\s+/).filter(Boolean));
const show = (cs: readonly Card[]) => cs.map((c) => `${c.rank}${c.suit}`).join(' ');
const check = (engine: number, textbook: number) => (engine === textbook ? '✓' : '✗ MISMATCH');

const out: string[] = [];
const w = (line = '') => out.push(line);

w('# Deer Camp Cribbage — engine check worksheet');
w();
w('_Generated by `npm run worksheet`. Every value is live engine output._');
w();
w('Use this to satisfy the Phase 1 acceptance gate (REQUIREMENTS Section 9):');
w('check these by hand, then try a few of your own with `npm run score -- <4 cards> <starter>`');
w('and `npm run deal`. The **Textbook** column is the independently-known answer —');
w('every ✓ means the engine agrees with it.');

// ---------------------------------------------------------------------------
// 1. Hand scoring (the show)
// ---------------------------------------------------------------------------
w();
w('## 1. Hand scoring (the show)');
w();
w('| Hand | Starter | Crib? | Engine | Textbook | OK | Breakdown |');
w('|---|---|---|---|---|---|---|');

interface HandCase {
  hand: string;
  starter: string;
  crib?: boolean;
  textbook: number;
  note?: string;
}
const handCases: HandCase[] = [
  { hand: '5C 5D 5H JS', starter: '5S', textbook: 29, note: 'perfect hand' },
  { hand: '4C 4D 5H 6S', starter: '6C', textbook: 24, note: 'double-double run' },
  { hand: '7C 7D 8H 8S', starter: '9C', textbook: 24, note: 'double-double run + 15s' },
  { hand: '7C 8D 8H 9S', starter: '9C', textbook: 20, note: 'the old Section-8 typo hand' },
  { hand: '4D 5S 6C JH', starter: '5H', textbook: 17, note: 'the mockup hand' },
  { hand: '2C 4D 6H 8S', starter: 'KC', textbook: 0, note: 'zero hand' },
  { hand: '2H 4H 6H 8H', starter: 'KS', textbook: 4, note: '4-card hand flush' },
  { hand: '2H 4H 6H 8H', starter: 'KH', textbook: 5, note: 'flush + matching starter' },
  { hand: '2H 4H 6H 8H', starter: 'KS', crib: true, textbook: 0, note: '4-card crib flush (needs 5)' },
  { hand: '2H 4H 6H 8H', starter: 'KH', crib: true, textbook: 5, note: '5-card crib flush' },
  { hand: 'JH 3C 7D KS', starter: 'AH', textbook: 1, note: 'nobs only (J matches starter suit)' },
];
for (const tc of handCases) {
  const score = scoreHand(h(tc.hand), h(tc.starter)[0]!, tc.crib ?? false);
  w(
    `| ${tc.hand} | ${tc.starter} | ${tc.crib ? 'yes' : 'no'} | ${score.total} | ${tc.textbook} | ` +
      `${check(score.total, tc.textbook)} | ${describeScore(score)}${tc.note ? ` _(${tc.note})_` : ''} |`,
  );
}
w();
w('Note: a Jack as the **starter** is "his heels" (2 to the dealer), which is a');
w('deal-time peg, not part of hand counting — so a hand with a Jack starter and no');
w('other scoring counts 0 here.');

// ---------------------------------------------------------------------------
// 2. Pegging (per card)
// ---------------------------------------------------------------------------
w();
w('## 2. Pegging — points for the card just played');
w();
w('| Series already down | Card played | Count after | Engine pts | Textbook | OK |');
w('|---|---|---|---|---|---|');

interface PegCase {
  before: string;
  card: string;
  textbook: number;
  note?: string;
}
const pegCases: PegCase[] = [
  { before: '7C', card: '8D', textbook: 2, note: 'makes 15' },
  { before: 'KC 5D 6H', card: 'KS', textbook: 2, note: 'makes 31 (2, not 3)' },
  { before: '7C', card: '7D', textbook: 2, note: 'pair' },
  { before: '7C 7D', card: '7H', textbook: 6, note: 'three of a kind' },
  { before: '7C 7D 7H', card: '7S', textbook: 12, note: 'four of a kind' },
  { before: '5C 3D', card: '4H', textbook: 3, note: 'run of 3, out of order' },
  { before: '4C 6D 5H', card: '3S', textbook: 4, note: 'run of 4' },
  { before: '3C 4D 5H', card: '9S', textbook: 0, note: 'run broken by an interrupting card' },
];
for (const pc of pegCases) {
  const sc = scorePegCard(h(pc.before), h(pc.card)[0]!);
  w(
    `| ${pc.before} | ${pc.card} | ${sc.total} | ${sc.points} | ${pc.textbook} | ` +
      `${check(sc.points, pc.textbook)}${pc.note ? ` _(${pc.note})_` : ''} |`,
  );
}

// ---------------------------------------------------------------------------
// 3. Counting out
// ---------------------------------------------------------------------------
w();
w('## 3. Counting out (the non-dealer counts first and can win mid-show)');
w();
const co = countShow({
  playerCount: 2,
  hands: [h('2C 3C 4C 6C'), h('5C 5D 5H JS')],
  crib: h('7C 8C 9C 10C'),
  starter: h('5S')[0]!,
  dealerSeat: 0,
  unitScoresBefore: [118, 115],
  target: 121,
});
w('Dealer = seat 0, so seat 1 (non-dealer) counts first. Scores before the show:');
w('seat 0 = 118, seat 1 = 115. Seat 1 holds the 29 hand.');
w();
w('| Step | Source | Points | Unit total after | Game over? |');
w('|---|---|---|---|---|');
co.steps.forEach((s, i) => {
  w(
    `| ${i + 1} | ${s.source === 'crib' ? 'crib' : `seat ${s.source}`} | ${s.score.total} | ` +
      `${s.unitScoreAfter} | ${s.won ? 'YES — wins' : 'no'} |`,
  );
});
w();
w(`Engine stops the moment seat 1 reaches 121: it counts **${co.steps.length} hand(s)** and`);
w(`the dealer never counts. Winner = seat **${co.winner}**. (Textbook: seat 1 wins, 1 step.)`);

// ---------------------------------------------------------------------------
// 4. Discard grading (eyeball the rankings)
// ---------------------------------------------------------------------------
w();
w('## 4. Discard grading — does the best throw make cribbage sense?');
w();

function discardTable(label: string, dealt: string, cribIsMine: boolean) {
  const grade = gradeDiscard({
    playerCount: 2,
    dealt: h(dealt),
    chosenDiscard: h(dealt).slice(0, 2),
    cribIsMine,
    seed: 'worksheet:fixed',
  });
  const values = grade.options.map((o) => o.value);
  w(`**${label}** — dealt \`${dealt}\`, crib is ${cribIsMine ? 'yours' : "the opponent's"}:`);
  w();
  w('| Throw | Keep | Exp. hand | Exp. crib | Value | Gave away | Rank |');
  w('|---|---|---|---|---|---|---|');
  for (const o of grade.options) {
    const gaveAway = grade.best.value - o.value;
    w(
      `| ${show(o.discard)} | ${show(o.keep)} | ${o.expectedHand.toFixed(2)} | ` +
        `${o.expectedCrib.toFixed(2)} | ${o.value.toFixed(2)} | ${gaveAway.toFixed(2)} | ` +
        `${rankPhrase(rankOf(o.value, values))} |`,
    );
  }
  w();
}
discardTable('Four 5s and a Jack', '5C 5D 5H JS 2C 9D', true);
discardTable('A middling hand', '4H 5S 6C 7D 9H 10C', true);
w('Sanity checks: keeping the four 5s + Jack should be the top throw by a mile;');
w('with your own crib the engine should lean toward feeding it good cards, and');
w('the "gave away" column should be 0.00 for the best option and grow downward.');

// ---------------------------------------------------------------------------
// 5. Hindsight (what-if) + verdict
// ---------------------------------------------------------------------------
w();
w('## 5. Hindsight at the cut + verdict');
w();
const hsDealt = '5C 5D 5H JS 2C 9D';
const hsThrow = '2C 9D';
const hsStarter = '5S';
const hs = hindsightAtCut({
  playerCount: 2,
  dealt: h(hsDealt),
  chosenDiscard: h(hsThrow),
  starter: h(hsStarter)[0]!,
});
const grade = gradeDiscard({
  playerCount: 2,
  dealt: h(hsDealt),
  chosenDiscard: h(hsThrow),
  cribIsMine: true,
  seed: 'worksheet:fixed',
});
const rightThrow = grade.rank.position === 1;
const favored = cutFavored(hs);
const v = verdict(rightThrow, favored);
w(`Dealt \`${hsDealt}\`, threw \`${hsThrow}\`, cut \`${hsStarter}\`:`);
w();
w(`- Hindsight best keep: \`${show(hs.best.keep)}\` worth **${hs.best.value}** with this cut`);
w(`- You actually kept: \`${show(hs.actual.keep)}\` worth **${hs.actual.value}**`);
w(`- Spread: **${hs.spread}**`);
w(`- Grader says right throw (rank 1)? **${rightThrow}**; cut favored it? **${favored}**`);
w(`- Verdict: **${v.text}**`);
w();
w("_(Keeping the four 5s + Jack is both the grader's best throw and the hindsight");
w('best with a 5 cut, so the verdict is "Called it".)_');

w();
w('---');
w('_Luck baselines are simulation averages, not hand-checkable; they are verified');
w('separately by `npm run test:slow` (zero-mean) and regenerated at scale with');
w('`npm run gen:baselines`._');

const here = dirname(fileURLToPath(import.meta.url));
const docsDir = join(here, '..', '..', '..', 'docs');
mkdirSync(docsDir, { recursive: true });
const file = join(docsDir, 'ENGINE_CHECK.md');
writeFileSync(file, out.join('\n') + '\n');
console.error(`wrote ${file}`);
