/**
 * GENERATED by scripts/generate-baselines.ts — do not edit by hand.
 * Luck baselines for 4A.7. Regenerate with: npm run gen:baselines
 */

import { type BaselineSet } from './baseline-cases.js';

export const BASELINES: BaselineSet = {
  meta: {
    generatedAt: "2026-10-06T23:14:35.109Z",
    dealLuckSamples: 100000,
    peggingSamples: 100000,
    cribIterations: 120,
  },
  dealLuck: {
      "2p-dealer": 13.336151242753859,
      "2p-nondealer": 3.9649940942029316,
      "3p-dealer": 11.475853304964474,
      "3p-nondealer": 2.125586275709253,
      "4p-dealer": 11.449136780141862,
      "4p-nondealer": 2.119468664007095
  },
  peggingLuck: {
      "2p-dealer": 3.82495,
      "2p-nondealer": 2.53754,
      "3p-dealer": 4.31702,
      "3p-nondealer": 2.695535,
      "4p-dealer": 7.30738,
      "4p-nondealer": 6.08561
  },
};
