/**
 * GENERATED by scripts/generate-baselines.ts — do not edit by hand.
 * Luck baselines for 4A.7. Regenerate with: npm run gen:baselines
 */

import { type BaselineSet } from './baseline-cases.js';

export const BASELINES: BaselineSet = {
  meta: {
    generatedAt: "2026-10-06T17:56:42.522Z",
    dealLuckSamples: 500,
    peggingSamples: 3000,
    cribIterations: 120,
  },
  dealLuck: {
      "2p-dealer": 13.37430289855072,
      "2p-nondealer": 4.090497101449281,
      "3p-dealer": 11.509085460992903,
      "3p-nondealer": 1.9052707446808514,
      "4p-dealer": 11.605489539007102,
      "4p-nondealer": 2.2380652482269476
  },
  peggingLuck: {
      "2p-dealer": 3.7943333333333333,
      "2p-nondealer": 2.4766666666666666,
      "3p-dealer": 4.343666666666667,
      "3p-nondealer": 2.6868333333333334,
      "4p-dealer": 7.258333333333334,
      "4p-nondealer": 5.971333333333333
  },
};
